"""
rejudge_metrics.py
==================
Re-evaluates all (case, model) SOAP outputs using an updated judge prompt that
more closely follows the definitions from the reference paper.

Changes vs. the original evaluate_models.py judge:
  - Judge model  : gemini-3.5-flash-lite  (500 RPD limit — no quota risk)
  - Score scale  : 0–100 (percentage)     (paper uses percentage scores)
  - Metric names :
      clinical_fidelity     → same name, updated prompt (align with paper definition)
      logical_consistency   → same name, updated prompt (align with paper definition)
      predictive_accuracy   → RENAMED to soap_structural_fidelity
                              (paper's predictive accuracy requires ML classifiers
                               with 200+ samples; with 5 cases that is not feasible.
                               We instead measure SOAP structural/semantic fidelity
                               against the ground truth SOAP — an equivalent measure
                               for an STT extraction task.)

This script reads saved SOAP CSVs from disk — NO OpenAI API calls are made.
Only Gemini (gemini-3.5-flash-lite) is called for judging.

Overwrites:
  - metrics_output/{case}_{safe_model}.json  (new metric names + 0-100 scale)
  - model_comparison_metrics.csv             (new column: soap_structural_fidelity)
"""

import os
import sys
import json
import csv
import time
import traceback
from pathlib import Path
from dotenv import load_dotenv

from google import genai
from google.genai import types

load_dotenv()

BASE_DIR         = Path(__file__).parent
SOURCE_DIR       = BASE_DIR.parent
TRANSCRIPT_DIR   = SOURCE_DIR.parent / 'audio_sample' / 'audio_recordings' / 'Clean_Transcripts'
PREDICTED_DIR    = BASE_DIR / 'predicted'
GROUND_TRUTH_DIR = BASE_DIR / 'ground_truth'
METRICS_DIR      = BASE_DIR / 'metrics_output'
METRICS_CSV      = BASE_DIR / 'model_comparison_metrics.csv'

MODELS = [
    'gemini-3.1-flash-lite',
    'gemini-3.5-flash',
    'gpt-5.6-terra',
]
CASES = ['CAR0001', 'MSK0005', 'RES0050', 'GAS0003', 'DER0001']

# New judge: gemini-3.5-flash-lite — 500 RPD, fresh quota
JUDGE_MODEL = 'gemini-3.5-flash-lite'


# ── Helpers ───────────────────────────────────────────────────────────────────

def get_ground_truth_transcript(case_id):
    txt_path = TRANSCRIPT_DIR / f"{case_id}.txt"
    if not txt_path.exists():
        return ""
    return txt_path.read_text(encoding='utf-8')


def get_ground_truth_soap(case_id):
    csv_path = GROUND_TRUTH_DIR / f"{case_id}_soap.csv"
    if not csv_path.exists():
        return ""
    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        rows = list(reader)
        return json.dumps(rows[0], indent=2) if rows else ""


def load_predicted_soap(case_id, safe_model):
    """Load the saved predicted SOAP CSV as a dict."""
    soap_path = PREDICTED_DIR / safe_model / f"{case_id}_soap.csv"
    if not soap_path.exists():
        raise FileNotFoundError(f"Missing predicted SOAP: {soap_path}")
    with open(soap_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        rows = list(reader)
        return dict(rows[0]) if rows else {}


def _parse_judge_response(raw_text):
    """Strip markdown fences and parse JSON from judge response."""
    text = raw_text.strip()
    if text.startswith('`'):
        lines = text.split('\n')
        text = '\n'.join(lines[1:-1] if lines[-1].strip() == '```' else lines[1:])
    return json.loads(text.strip())


# ── Judge (updated prompts, 0–100 scale) ─────────────────────────────────────

def evaluate_soap_paper_aligned(gt_transcript, gt_soap, predicted_soap_dict):
    """
    Grade a predicted SOAP using prompts aligned with the reference paper.

    Metrics (0–100 percentage scale):
      1. clinical_fidelity       — clinical vitals/symptoms align with transcript facts
      2. logical_consistency     — internal consistency of data points within the record
      3. soap_structural_fidelity — structural/semantic match to ground truth SOAP
                                    (replaces 'predictive_accuracy'; paper's version
                                    requires ML classifiers not feasible with 5 cases)

    Judge: gemini-3.5-flash-lite (500 RPD, no quota risk)
    Retries: up to 8 attempts with exponential back-off (15s → 30s → 60s → 120s...)
    Fallback: None needed — flash-lite has ample quota
    """
    client = genai.Client()
    predicted_soap_json = json.dumps(predicted_soap_dict, indent=2)

    prompt = f"""You are an expert clinical documentation evaluator. Your task is to evaluate a predicted SOAP (Subjective, Objective, Assessment, Plan) report generated by an AI model from a doctor-patient consultation transcript.

Evaluate using the following three metrics, each scored as a percentage from 0 to 100:

---

METRIC 1 — Clinical Fidelity (0–100%):
Definition (from reference paper): "Clinical fidelity determines whether the generated clinical vitals and symptoms align strictly with the provided information."
For this task: Score how accurately the predicted SOAP captures the clinical facts stated in the Ground Truth Transcript. Penalise for:
  - Omitted symptoms, diagnoses, medications, or clinical details that were mentioned
  - Hallucinated facts that were NOT mentioned in the transcript
  - Incorrect values (wrong dosage, wrong body part, wrong duration)

METRIC 2 — Logical Consistency (0–100%):
Definition (from reference paper): "Logical consistency measures how logically accurate and consistent the individual data points are in relation to one another within a single medical record."
For this task: Score whether the SOAP fields form a coherent, non-contradictory clinical narrative. Penalise for:
  - A Plan that contradicts the Assessment
  - A Diagnosis that is not supported by the Subjective/Objective findings
  - Inconsistent medication entries (prescribed vs. current)
  - Internal contradictions between any two fields

METRIC 3 — SOAP Structural Fidelity (0–100%):
Definition: How closely the predicted SOAP matches the Ground Truth SOAP in structure, completeness of fields, and semantic meaning.
Note: The reference paper measures "predictive accuracy" via ML classifiers trained on 200+ records. With only 5 cases, classifier training is not feasible. This metric is the equivalent measure for an STT extraction task — it assesses whether the AI produced the correct structured output relative to the reference.
Penalise for:
  - Missing or empty fields that are populated in the ground truth
  - Semantically different diagnoses or plans
  - Significant differences in detail level or clinical specificity

---

Ground Truth Transcript:
{gt_transcript}

Ground Truth SOAP:
{gt_soap}

Predicted SOAP:
{predicted_soap_json}

---

Output MUST be a valid JSON object strictly matching this schema (integer percentages 0–100):
{{
  "clinical_fidelity": <int 0-100>,
  "logical_consistency": <int 0-100>,
  "soap_structural_fidelity": <int 0-100>
}}
"""
    max_attempts = 8
    for attempt in range(max_attempts):
        try:
            response = client.models.generate_content(
                model=JUDGE_MODEL,
                contents=prompt,
                config=types.GenerateContentConfig(
                    response_mime_type="application/json",
                )
            )
            result = _parse_judge_response(response.text)
            if attempt > 0:
                print(f"    [Judge] ✅ Succeeded on attempt {attempt+1}")
            return result
        except Exception as e:
            wait = min(15 * (2 ** attempt), 120)   # 15, 30, 60, 120, 120, ...
            print(f"    [Judge] Error (attempt {attempt+1}/{max_attempts}): {e}")
            print(f"    [Judge] Waiting {wait}s...")
            time.sleep(wait)

    print("    [Judge] Failed after all retries — returning zeros.")
    return {"clinical_fidelity": 0, "logical_consistency": 0, "soap_structural_fidelity": 0}


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    print("=" * 65)
    print("  Medical STT — Re-judge with Paper-Aligned Metrics")
    print(f"  Judge  : {JUDGE_MODEL}")
    print(f"  Scale  : 0–100 (percentage)")
    print(f"  Metric 3: soap_structural_fidelity  (renamed from predictive_accuracy)")
    print("=" * 65)

    all_results = []

    for case_id in CASES:
        print(f"\n{'─'*60}")
        print(f"  Conversation: {case_id}")
        print(f"{'─'*60}")

        gt_transcript = get_ground_truth_transcript(case_id)
        gt_soap       = get_ground_truth_soap(case_id)

        for model in MODELS:
            safe_model  = model.replace('/', '_').replace(':', '_')
            metric_file = METRICS_DIR / f"{case_id}_{safe_model}.json"

            print(f"\n  Model: {model}")

            try:
                predicted_soap = load_predicted_soap(case_id, safe_model)
            except FileNotFoundError as e:
                print(f"    [SKIP] {e}")
                continue

            print(f"    → Grading with {JUDGE_MODEL}...")
            scores = evaluate_soap_paper_aligned(gt_transcript, gt_soap, predicted_soap)

            if scores.get('clinical_fidelity') == 0 and scores.get('logical_consistency') == 0:
                print(f"    [ERROR] All-zero scores — skipping checkpoint write.")
                continue

            print(
                f"    ✅ Clinical Fidelity: {scores['clinical_fidelity']}% | "
                f"Logical Consistency: {scores['logical_consistency']}% | "
                f"SOAP Structural Fidelity: {scores['soap_structural_fidelity']}%"
            )

            result_data = {
                'case_id': case_id,
                'model':   model,
                'clinical_fidelity':        scores.get('clinical_fidelity', 0),
                'logical_consistency':      scores.get('logical_consistency', 0),
                'soap_structural_fidelity': scores.get('soap_structural_fidelity', 0),
            }
            with open(metric_file, 'w', encoding='utf-8') as f:
                json.dump(result_data, f, indent=2)
            print(f"    ✅ Checkpoint updated: {metric_file.name}")

            all_results.append(result_data)

    print(f"\n{'='*65}")
    print("  ✅ Re-judging complete!")
    print(f"{'='*65}")

    # Regenerate combined CSV with new metric names
    with open(METRICS_CSV, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=[
            'case_id', 'model',
            'clinical_fidelity', 'logical_consistency', 'soap_structural_fidelity'
        ])
        writer.writeheader()
        writer.writerows(all_results)

    total_expected = len(CASES) * len(MODELS)
    print(f"\n  ✅ Combined metrics → {METRICS_CSV}")
    print(f"     Rows: {len(all_results)} / {total_expected} expected")


if __name__ == '__main__':
    main()
